//! Generated by tool/check_suite_sync.py from fuego-suite 3d4b10adb76ed9b925bcd34746872e825e8fa4fd.
//! Do not edit by hand: run `python3 tool/check_suite_sync.py sync --suite <fuego-suite>`.
#![allow(dead_code, clippy::all)]

pub const SUITE_COMMIT: &str = "3d4b10adb76ed9b925bcd34746872e825e8fa4fd";

/// CryptoNoteConfig.h: `UINT64_C(10000000)`
pub const COIN: u64 = 10000000;
/// CryptoNoteConfig.h: `MINIMUM_FEE_8KH`
pub const MINIMUM_FEE: u64 = 8000;
/// CryptoNoteConfig.h: `UINT64_C(1000)`
pub const DEFAULT_DUST_THRESHOLD: u64 = 1000;
/// CryptoNoteConfig.h: `2`
pub const MIN_TX_MIXIN_SIZE_V2: u64 = 2;
/// CryptoNoteConfig.h: `8`
pub const MIN_TX_MIXIN_SIZE_V10: u64 = 8;
/// CryptoNoteConfig.h: `32`
pub const MAX_TX_MIXIN_SIZE: u64 = 32;
/// CryptoNoteConfig.h: `500000000`
pub const CRYPTONOTE_MAX_BLOCK_NUMBER: u64 = 500000000;
/// CryptoNoteConfig.h: `3`
pub const CRYPTONOTE_DEFAULT_TX_SPENDABLE_AGE: u64 = 3;
/// CryptoNoteConfig.h: `60`
pub const CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW: u64 = 60;
/// CryptoNoteConfig.h: `1`
pub const CRYPTONOTE_LOCKED_TX_ALLOWED_DELTA_BLOCKS: u64 = 1;
/// CryptoNoteConfig.h: `DIFFICULTY_TARGET_DRGL * CRYPTONOTE_LOCKED_TX_ALLOWED_DELTA_BLOCKS`
pub const CRYPTONOTE_LOCKED_TX_ALLOWED_DELTA_SECONDS: u64 = 81;
/// CryptoNoteConfig.h: `1753191`
pub const CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX: u64 = 1753191;
/// CryptoNoteConfig.h: `1075740`
pub const CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX_TESTNET: u64 = 1075740;
/// CryptoNoteConfig.h: `900`
pub const EPOCH_DURATION_BLOCKS: u64 = 900;
/// CryptoNoteConfig.h: `10`
pub const TESTNET_EPOCH_DURATION_BLOCKS: u64 = 10;
/// CryptoNoteConfig.h: `CD_MIN_EPOCHS * EPOCH_DURATION_BLOCKS`
pub const DEPOSIT_MIN_TERM: u32 = 5400;
/// CryptoNoteConfig.h: `CD_MAX_EPOCHS * EPOCH_DURATION_BLOCKS`
pub const DEPOSIT_MAX_TERM: u32 = 64800;
/// CryptoNoteConfig.h: `TESTNET_CD_MIN_EPOCHS * TESTNET_EPOCH_DURATION_BLOCKS`
pub const TESTNET_DEPOSIT_MIN_TERM: u32 = 10;
/// CryptoNoteConfig.h: `TESTNET_CD_MAX_EPOCHS * TESTNET_EPOCH_DURATION_BLOCKS`
pub const TESTNET_DEPOSIT_MAX_TERM: u32 = 720;
/// CryptoNoteConfig.h: `((uint32_t)(-1))`
pub const HEAT_TERM: u32 = 4294967295;
/// CryptoNoteConfig.h: `0xFFFFFFFD`
pub const DEPOSIT_TERM_LP: u32 = 4294967293;
/// CryptoNoteConfig.h: `0x504F4C58`
pub const DEPOSIT_TERM_POOL_XFG: u32 = 1347374168;
/// CryptoNoteConfig.h: `0x504F4C48`
pub const DEPOSIT_TERM_POOL_HEAT: u32 = 1347374152;
/// CryptoNoteConfig.h: `0x53575258`
pub const DEPOSIT_TERM_SWAP_RECEIVE_XFG: u32 = 1398231640;
/// CryptoNoteConfig.h: `0x44494D47`
pub const DIGM_TERM: u32 = 1145654599;
/// CryptoNoteConfig.h: `1000000`
pub const HEAT_MINT_MIN_HEAT: u64 = 1000000;
/// CryptoNoteConfig.h: `0`
pub const HEAT_MINT_PREMIUM_BPS: u64 = 0;
/// CryptoNoteConfig.h: `100`
pub const HEARTH_FEE_BPS: u64 = 100;
/// CryptoNoteConfig.h: `10000`
pub const HEARTH_FEE_DIVISOR: u64 = 10000;
/// CryptoNoteConfig.h: `100`
pub const SWAP_FEE_RATE_BPS: u64 = 100;
/// CryptoNoteConfig.h: `10000`
pub const SWAP_FEE_RATE_DIVISOR: u64 = 10000;
/// CryptoNoteConfig.h: `COIN`
pub const ALIAS_REGISTRATION_FEE: u64 = 10000000;
/// CryptoNoteConfig.h: `1000`
pub const ALIAS_REGISTRATION_FEE_MAX_RANDOM: u64 = 1000;
/// CryptoNoteConfig.h: `1003000`
pub const UPGRADE_HEIGHT_V10: u32 = 1003000;
/// CryptoNoteConfig.h: `1111111`
pub const UPGRADE_HEIGHT_V11: u32 = 1111111;
/// CryptoNoteConfig.h: `1500000`
pub const UPGRADE_HEIGHT_V12: u32 = 1500000;
/// CryptoNoteConfig.h: `"fireVHx639SLMhzmBoJ8drTXbVyv2eRG6A8aMLc1taTiRNwk8pnwXpBDUSjH1dT5fg7yVVZrKkvm31CmigAMdVDg7sgxJmAUNp"`
pub const FUEGO_DEV_FUND_ADDRESS: &str = "fireVHx639SLMhzmBoJ8drTXbVyv2eRG6A8aMLc1taTiRNwk8pnwXpBDUSjH1dT5fg7yVVZrKkvm31CmigAMdVDg7sgxJmAUNp";

/// Currency.cpp testnet m_upgradeHeightV2
pub const TESTNET_UPGRADE_HEIGHT_V2: u32 = 2;
/// Currency.cpp testnet m_upgradeHeightV3
pub const TESTNET_UPGRADE_HEIGHT_V3: u32 = 3;
/// Currency.cpp testnet m_upgradeHeightV4
pub const TESTNET_UPGRADE_HEIGHT_V4: u32 = 4;
/// Currency.cpp testnet m_upgradeHeightV5
pub const TESTNET_UPGRADE_HEIGHT_V5: u32 = 5;
/// Currency.cpp testnet m_upgradeHeightV6
pub const TESTNET_UPGRADE_HEIGHT_V6: u32 = 6;
/// Currency.cpp testnet m_upgradeHeightV7
pub const TESTNET_UPGRADE_HEIGHT_V7: u32 = 17;
/// Currency.cpp testnet m_upgradeHeightV8
pub const TESTNET_UPGRADE_HEIGHT_V8: u32 = 18;
/// Currency.cpp testnet m_upgradeHeightV9
pub const TESTNET_UPGRADE_HEIGHT_V9: u32 = 19;
/// Currency.cpp testnet m_upgradeHeightV10
pub const TESTNET_UPGRADE_HEIGHT_V10: u32 = 25;
/// Currency.cpp testnet m_upgradeHeightV11
pub const TESTNET_UPGRADE_HEIGHT_V11: u32 = 30;
/// Currency.cpp testnet m_upgradeHeightV12
pub const TESTNET_UPGRADE_HEIGHT_V12: u32 = 180;

/// TransactionExtra.h tags.
pub mod tx_extra {
    pub const TX_EXTRA_ALIAS: u8 = 0xEA;
    pub const TX_EXTRA_ALIAS_RELEASE: u8 = 0xEC;
    pub const TX_EXTRA_ALIAS_TRANSFER: u8 = 0xED;
    pub const TX_EXTRA_AMM_ADD_LIQ: u8 = 0xF1;
    pub const TX_EXTRA_AMM_CLAIM: u8 = 0xF4;
    pub const TX_EXTRA_AMM_COMPOUND: u8 = 0xF3;
    pub const TX_EXTRA_AMM_LP_ADD_AUTH: u8 = 0xF7;
    pub const TX_EXTRA_AMM_LP_REM_AUTH: u8 = 0xF8;
    pub const TX_EXTRA_AMM_REM_LIQ: u8 = 0xF2;
    pub const TX_EXTRA_AMM_SWAP: u8 = 0xF0;
    pub const TX_EXTRA_AMM_SWAP_AUTH: u8 = 0xF6;
    pub const TX_EXTRA_BURN_RECEIPT: u8 = 0x18;
    pub const TX_EXTRA_CD_BONUS_CLAIM: u8 = 0xD6;
    pub const TX_EXTRA_DEPOSIT_SECRET: u8 = 0xD5;
    pub const TX_EXTRA_DIGM_ALBUM: u8 = 0x0A;
    pub const TX_EXTRA_DIGM_CURATOR: u8 = 0x0C;
    pub const TX_EXTRA_DIGM_CURATOR_COIN: u8 = 0x1C;
    pub const TX_EXTRA_DIGM_LISTEN_RIGHTS: u8 = 0x0B;
    pub const TX_EXTRA_DIGM_MINT: u8 = 0xA8;
    pub const TX_EXTRA_HEAT_COMMITMENT: u8 = 0x08;
    pub const TX_EXTRA_HEAT_MINT_AUTH: u8 = 0xF5;
    pub const TX_EXTRA_HEAT_SEND_AUTH: u8 = 0xF9;
    pub const TX_EXTRA_LEGACY_BOND: u8 = 0xCB;
    pub const TX_EXTRA_LEGACY_BOND_CLAIM: u8 = 0xCC;
    pub const TX_EXTRA_LIMIT_DEPOSIT: u8 = 0xFB;
    pub const TX_EXTRA_LIMIT_WITHDRAW: u8 = 0xFE;
    pub const TX_EXTRA_MARKET_BUY_AUTH: u8 = 0xFC;
    pub const TX_EXTRA_MARKET_SELL_AUTH: u8 = 0xFD;
    pub const TX_EXTRA_MERGE_MINING_TAG: u8 = 0x03;
    pub const TX_EXTRA_MESSAGE_TAG: u8 = 0x04;
    pub const TX_EXTRA_NONCE: u8 = 0x02;
    pub const TX_EXTRA_NONCE_MAX_COUNT: u8 = 0xFF;
    pub const TX_EXTRA_NONCE_PAYMENT_ID: u8 = 0x00;
    pub const TX_EXTRA_ORDER_CANCEL: u8 = 0x0F;
    pub const TX_EXTRA_ORDER_PLACE: u8 = 0xFA;
    pub const TX_EXTRA_PADDING_MAX_COUNT: u8 = 0xFF;
    pub const TX_EXTRA_SIMPLE_CD: u8 = 0xCD;
    pub const TX_EXTRA_TAG_PADDING: u8 = 0x00;
    pub const TX_EXTRA_TAG_PUBKEY: u8 = 0x01;
    pub const TX_EXTRA_TREASURY_FUND: u8 = 0xFF;
    pub const TX_EXTRA_TTL: u8 = 0x05;
    pub const TX_EXTRA_YIELD_COMMITMENT: u8 = 0x07;
}

/// fuegod routes (RpcServer.cpp): HTTP endpoints and /json_rpc methods.
pub mod rpc {
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum Transport {
        /// KV-binary body (`binMethod`).
        Binary,
        /// JSON body, JSON response (`jsonMethod`).
        Json,
        /// JSON body gated by the swap auth token (`jsonMethodSwapAuth`).
        JsonSwapAuth,
        /// The JSON-RPC 2.0 dispatcher itself.
        JsonRpc,
    }

    pub const HTTP_ROUTES: &[(&str, Transport)] = &[
        ("/accept", Transport::JsonSwapAuth),
        ("/addswapfee", Transport::JsonSwapAuth),
        ("/amm_pool_info", Transport::Json),
        ("/amm_quote", Transport::Json),
        ("/cancelorder", Transport::JsonSwapAuth),
        ("/cancelswap", Transport::JsonSwapAuth),
        ("/check_commitment_exists", Transport::Json),
        ("/estimate_cd_yield", Transport::Json),
        ("/feeaddress", Transport::Json),
        ("/get_alias", Transport::Json),
        ("/get_alias_by_address", Transport::Json),
        ("/get_all_aliases", Transport::Json),
        ("/get_block_range", Transport::Json),
        ("/get_commitment", Transport::Json),
        ("/get_commitment_leaves", Transport::Json),
        ("/get_commitment_merkle_proof", Transport::Json),
        ("/get_commitment_merkle_root", Transport::Json),
        ("/get_commitment_stats", Transport::Json),
        ("/get_epoch_history", Transport::Json),
        ("/get_fee_pool_info", Transport::Json),
        ("/get_fuego_price", Transport::Json),
        ("/get_limit_orders", Transport::Json),
        ("/get_maturing_deposits", Transport::Json),
        ("/get_o_indexes.bin", Transport::Binary),
        ("/get_outs_json", Transport::Json),
        ("/get_pool_changes.bin", Transport::Binary),
        ("/get_pool_changes_lite.bin", Transport::Binary),
        ("/get_treasury_info", Transport::Json),
        ("/getactiveswaps", Transport::Json),
        ("/getblocks.bin", Transport::Binary),
        ("/getdeposits", Transport::Json),
        ("/getethereal", Transport::Json),
        ("/getheight", Transport::Json),
        ("/getinfo", Transport::Json),
        ("/getorderbook", Transport::Json),
        ("/getrandom_commitment_outs.bin", Transport::Binary),
        ("/getrandom_outs.bin", Transport::Binary),
        ("/getrandom_outs_json", Transport::Json),
        ("/getswapoffers", Transport::Json),
        ("/getswapprice", Transport::Json),
        ("/getswaprequests", Transport::Json),
        ("/getswapstatus", Transport::Json),
        ("/getswaptrades", Transport::Json),
        ("/gettransactions", Transport::Json),
        ("/heat_metrics", Transport::Json),
        ("/initiate", Transport::JsonSwapAuth),
        ("/is_key_image_spent", Transport::Json),
        ("/json_rpc", Transport::JsonRpc),
        ("/listswaps", Transport::Json),
        ("/openorders", Transport::Json),
        ("/paymentid", Transport::Json),
        ("/peers", Transport::Json),
        ("/placeorder", Transport::JsonSwapAuth),
        ("/processswap", Transport::JsonSwapAuth),
        ("/queryblocks.bin", Transport::Binary),
        ("/queryblockslite.bin", Transport::Binary),
        ("/refundswap", Transport::JsonSwapAuth),
        ("/requestswap", Transport::JsonSwapAuth),
        ("/rollover_deposit", Transport::Json),
        ("/sendrawtransaction", Transport::Json),
        ("/start_mining", Transport::Json),
        ("/stop_daemon", Transport::Json),
        ("/stop_mining", Transport::Json),
        ("/submitswap", Transport::JsonSwapAuth),
    ];

    pub const JSON_RPC_METHODS: &[&str] = &[
        "check_reserve_proof",
        "check_tx_proof",
        "f_block_json",
        "f_blocks_list_json",
        "f_on_transactions_pool_json",
        "f_transaction_json",
        "getaltblockslist",
        "getblockcount",
        "getblockheaderbyhash",
        "getblockheaderbyheight",
        "getblocktemplate",
        "getcurrencyid",
        "getlastblockheader",
        "on_getblockhash",
        "submitblock",
    ];

    pub fn http_route(path: &str) -> Option<Transport> {
        HTTP_ROUTES.iter().find(|(p, _)| *p == path).map(|(_, t)| *t)
    }

    pub fn is_json_rpc_method(method: &str) -> bool {
        JSON_RPC_METHODS.contains(&method)
    }
}

/// fuegod request/response structs (CoreRpcServerCommandsDefinitions.h).
pub mod fuegod {
    use serde::{Deserialize, Serialize};

    /// COMMAND_RPC_SEND_RAW_TX::request
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct SendRawTxRequest {
        #[serde(rename = "tx_as_hex")]
        pub tx_as_hex: String,
    }

    /// COMMAND_RPC_SEND_RAW_TX::response
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct SendRawTxResponse {
        #[serde(rename = "status")]
        pub status: String,
    }

    /// COMMAND_RPC_AMM_POOL_INFO::request
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct AmmPoolInfoRequest {
    }

    /// COMMAND_RPC_AMM_POOL_INFO::response
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct AmmPoolInfoResponse {
        #[serde(rename = "reserve_xfg")]
        pub reserve_xfg: u64,
        #[serde(rename = "reserve_heat")]
        pub reserve_heat: u64,
        #[serde(rename = "total_lp_shares")]
        pub total_lp_shares: u64,
        #[serde(rename = "spot_price")]
        pub spot_price: u64,
        #[serde(rename = "epoch_swap_fees")]
        pub epoch_swap_fees: u64,
        #[serde(rename = "hearth_twap")]
        pub hearth_twap: u64,
        #[serde(rename = "height")]
        pub height: u64,
        #[serde(rename = "status")]
        pub status: String,
    }

    /// COMMAND_RPC_ESTIMATE_CD_YIELD::request
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct EstimateCdYieldRequest {
        #[serde(rename = "amount")]
        pub amount: u64,
        #[serde(rename = "creation_height")]
        pub creation_height: u32,
        #[serde(rename = "current_height")]
        pub current_height: u32,
        #[serde(rename = "term")]
        pub term: u32,
    }

    /// COMMAND_RPC_ESTIMATE_CD_YIELD::response
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct EstimateCdYieldResponse {
        #[serde(rename = "estimated_interest")]
        pub estimated_interest: u64,
        #[serde(rename = "effective_epochs")]
        pub effective_epochs: u64,
        #[serde(rename = "fee_pool_balance")]
        pub fee_pool_balance: u64,
        #[serde(rename = "cd_apy_vault_balance")]
        pub cd_apy_vault_balance: u64,
        #[serde(rename = "claimable_interest")]
        pub claimable_interest: u64,
        #[serde(rename = "base_interest")]
        pub base_interest: u64,
        #[serde(rename = "bonus_interest")]
        pub bonus_interest: u64,
        #[serde(rename = "bonus_vault_balance")]
        pub bonus_vault_balance: u64,
        #[serde(rename = "claimable_bonus")]
        pub claimable_bonus: u64,
        #[serde(rename = "pool_info_present")]
        pub pool_info_present: bool,
        #[serde(rename = "note")]
        pub note: String,
        #[serde(rename = "status")]
        pub status: String,
    }

    /// COMMAND_RPC_IS_KEY_IMAGE_SPENT::request
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct IsKeyImageSpentRequest {
        #[serde(rename = "key_image")]
        pub key_image: String,
    }

    /// COMMAND_RPC_IS_KEY_IMAGE_SPENT::response
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct IsKeyImageSpentResponse {
        #[serde(rename = "spent")]
        pub spent: bool,
        #[serde(rename = "status")]
        pub status: String,
    }

    /// COMMAND_RPC_GET_ALIAS::request
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct GetAliasRequest {
        #[serde(rename = "alias")]
        pub alias: String,
    }

    /// COMMAND_RPC_GET_ALIAS::response
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct GetAliasResponse {
        #[serde(rename = "alias")]
        pub alias: String,
        #[serde(rename = "address")]
        pub address: String,
        #[serde(rename = "address_hash")]
        pub address_hash: String,
        #[serde(rename = "registered_block")]
        pub registered_block: u32,
        #[serde(rename = "alias_type")]
        pub alias_type: u8,
        #[serde(rename = "found")]
        pub found: bool,
        #[serde(rename = "status")]
        pub status: String,
    }

}

/// walletd JSON-RPC messages (PaymentServiceJsonRpcMessages).
pub mod walletd {
    use serde::{Deserialize, Serialize};

    pub const GET_BALANCE: &str = "getBalance";
    pub const GET_STATUS: &str = "getStatus";
    pub const GET_ADDRESSES: &str = "getAddresses";
    pub const GET_TRANSACTIONS: &str = "getTransactions";
    pub const SEND_TRANSACTION: &str = "sendTransaction";
    pub const CREATE_INTEGRATED: &str = "createIntegrated";

    /// GetBalance::Request
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct GetBalanceRequest {
        #[serde(rename = "address")]
        pub address: String,
    }

    /// GetBalance::Response
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct GetBalanceResponse {
        #[serde(rename = "availableBalance")]
        pub available_balance: u64,
        #[serde(rename = "lockedAmount")]
        pub locked_amount: u64,
        #[serde(rename = "lockedDepositBalance")]
        pub locked_deposit_balance: u64,
        #[serde(rename = "unlockedDepositBalance")]
        pub unlocked_deposit_balance: u64,
        #[serde(rename = "lockedHeatBalance")]
        pub locked_heat_balance: u64,
        #[serde(rename = "unlockedHeatBalance")]
        pub unlocked_heat_balance: u64,
    }

    /// GetStatus::Request
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct GetStatusRequest {
    }

    /// GetStatus::Response
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct GetStatusResponse {
        #[serde(rename = "blockCount")]
        pub block_count: u32,
        #[serde(rename = "knownBlockCount")]
        pub known_block_count: u32,
        #[serde(rename = "lastBlockHash")]
        pub last_block_hash: String,
        #[serde(rename = "peerCount")]
        pub peer_count: u32,
        #[serde(rename = "depositCount")]
        pub deposit_count: u32,
        #[serde(rename = "transactionCount")]
        pub transaction_count: u32,
        #[serde(rename = "addressCount")]
        pub address_count: u32,
    }

    /// GetAddresses::Request
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct GetAddressesRequest {
    }

    /// GetAddresses::Response
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct GetAddressesResponse {
        #[serde(rename = "addresses")]
        pub addresses: Vec<String>,
    }

    /// GetTransactions::Request
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct GetTransactionsRequest {
        #[serde(rename = "addresses")]
        pub addresses: Vec<String>,
        #[serde(rename = "blockHash")]
        pub block_hash: String,
        #[serde(rename = "firstBlockIndex")]
        pub first_block_index: u32,
        #[serde(rename = "blockCount")]
        pub block_count: u32,
        #[serde(rename = "paymentId")]
        pub payment_id: String,
    }

    /// GetTransactions::Response
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct GetTransactionsResponse {
        #[serde(rename = "items")]
        pub items: Vec<TransactionsInBlockRpcInfo>,
    }

    /// TransactionsInBlockRpcInfo
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct TransactionsInBlockRpcInfo {
        #[serde(rename = "blockHash")]
        pub block_hash: String,
        #[serde(rename = "transactions")]
        pub transactions: Vec<TransactionRpcInfo>,
    }

    /// TransactionRpcInfo
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct TransactionRpcInfo {
        #[serde(rename = "state")]
        pub state: u8,
        #[serde(rename = "transactionHash")]
        pub transaction_hash: String,
        #[serde(rename = "blockIndex")]
        pub block_index: u32,
        #[serde(rename = "confirmations")]
        pub confirmations: u32,
        #[serde(rename = "timestamp")]
        pub timestamp: u64,
        #[serde(rename = "isBase")]
        pub is_base: bool,
        #[serde(rename = "unlockTime")]
        pub unlock_time: u64,
        #[serde(rename = "amount")]
        pub amount: i64,
        #[serde(rename = "fee")]
        pub fee: u64,
        #[serde(rename = "transfers")]
        pub transfers: Vec<TransferRpcInfo>,
        #[serde(rename = "extra")]
        pub extra: String,
        #[serde(rename = "firstDepositId")]
        pub first_deposit_id: u64,
        #[serde(rename = "depositCount")]
        pub deposit_count: u64,
        #[serde(rename = "paymentId")]
        pub payment_id: String,
    }

    /// TransferRpcInfo
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct TransferRpcInfo {
        #[serde(rename = "type")]
        pub r#type: u8,
        #[serde(rename = "address")]
        pub address: String,
        #[serde(rename = "amount")]
        pub amount: i64,
        #[serde(rename = "message")]
        pub message: String,
    }

    /// SendTransaction::Request
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct SendTransactionRequest {
        #[serde(rename = "addresses")]
        pub addresses: Vec<String>,
        #[serde(rename = "transfers")]
        pub transfers: Vec<WalletRpcOrder>,
        #[serde(rename = "changeAddress")]
        pub change_address: String,
        #[serde(rename = "fee")]
        pub fee: u64,
        #[serde(rename = "anonymity")]
        pub anonymity: u32,
        #[serde(rename = "extra")]
        pub extra: String,
        #[serde(rename = "paymentId")]
        pub payment_id: String,
        #[serde(rename = "unlockTime")]
        pub unlock_time: u64,
    }

    /// WalletRpcOrder
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct WalletRpcOrder {
        #[serde(rename = "message")]
        pub message: String,
        #[serde(rename = "address")]
        pub address: String,
        #[serde(rename = "amount")]
        pub amount: u64,
    }

    /// SendTransaction::Response
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct SendTransactionResponse {
        #[serde(rename = "transactionHash")]
        pub transaction_hash: String,
        #[serde(rename = "transactionSecretKey")]
        pub transaction_secret_key: String,
    }

    /// CreateIntegrated::Request
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct CreateIntegratedRequest {
        #[serde(rename = "address")]
        pub address: String,
        #[serde(rename = "payment_id")]
        pub payment_id: String,
    }

    /// CreateIntegrated::Response
    #[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
    #[serde(default)]
    pub struct CreateIntegratedResponse {
        #[serde(rename = "integrated_address")]
        pub integrated_address: String,
    }

}
