//! Fuego sub-addresses, ported from fuego-suite `src/crypto/subaddress.cpp`
//! (`deriveSubAddressKeys`), which WalletGreen uses.
//!
//! With master keys a (view) and b (spend), A = aG, B = bG, the sub-address
//! at (major, minor) is
//!   m = Hs("Sublime" || a || major_le32 || minor_le32)
//!   D = B + mG            sub-address spend public key
//!   C = A                 view public key is the master one
//!   b' = b + m (mod l)    sub-address spend secret key
//!
//! Senders treat it as an ordinary address (R = rG), and the receiver finds
//! outputs with the one master derivation aR: underive each output key and
//! look the result up among {B, D...}. Because C = A, every sub-address
//! carries the master view public key, so sub-addresses of one wallet are
//! linkable by anyone who sees two of them.

use crate::ref10::{
    ge_add, ge_frombytes_vartime, ge_p1p1_to_p3, ge_p3_to_cached, ge_p3_tobytes,
    ge_scalarmult_base, sc_add, sc_check, GeCached, GeP1P1, GeP3,
};
use crate::ring::{hash_to_scalar, secret_key_to_public_key};
use zeroize::Zeroize;

const DOMAIN: &[u8; 7] = b"Sublime";

#[derive(Clone)]
pub struct SubaddressKeys {
    /// D = B + mG
    pub spend_public: [u8; 32],
    /// C = A (master view public key)
    pub view_public: [u8; 32],
    /// b + m, when the master spend secret was supplied.
    pub spend_secret: Option<[u8; 32]>,
}

impl Drop for SubaddressKeys {
    fn drop(&mut self) {
        if let Some(s) = self.spend_secret.as_mut() {
            s.zeroize();
        }
    }
}

/// m = Hs("Sublime" || a || major || minor).
fn subaddress_scalar(view_secret: &[u8; 32], major: u32, minor: u32) -> [u8; 32] {
    let mut pre = [0u8; 7 + 32 + 8];
    pre[..7].copy_from_slice(DOMAIN);
    pre[7..39].copy_from_slice(view_secret);
    pre[39..43].copy_from_slice(&major.to_le_bytes());
    pre[43..47].copy_from_slice(&minor.to_le_bytes());
    let m = hash_to_scalar(&pre);
    pre.zeroize();
    m
}

/// Derive the sub-address keys at (major, minor). (0, 0) is the primary
/// address and is refused, as are invalid keys.
pub fn derive_subaddress_keys(
    view_secret: &[u8; 32],
    spend_public: &[u8; 32],
    spend_secret: Option<&[u8; 32]>,
    major: u32,
    minor: u32,
) -> Option<SubaddressKeys> {
    if (major, minor) == (0, 0) || !sc_check(view_secret) {
        return None;
    }
    let mut b_point = GeP3::default();
    if !ge_frombytes_vartime(&mut b_point, spend_public) {
        return None;
    }
    let mut m = subaddress_scalar(view_secret, major, minor);

    let mut m_g = GeP3::default();
    ge_scalarmult_base(&mut m_g, &m);
    let mut m_g_cached = GeCached::default();
    ge_p3_to_cached(&mut m_g_cached, &m_g);
    let mut sum = GeP1P1::default();
    ge_add(&mut sum, &b_point, &m_g_cached);
    let mut d = GeP3::default();
    ge_p1p1_to_p3(&mut d, &sum);
    let mut spend_pub = [0u8; 32];
    ge_p3_tobytes(&mut spend_pub, &d);

    let sub_secret = spend_secret.map(|b| {
        let mut out = [0u8; 32];
        sc_add(&mut out, b, &m);
        out
    });
    m.zeroize();

    Some(SubaddressKeys {
        spend_public: spend_pub,
        view_public: secret_key_to_public_key(view_secret),
        spend_secret: sub_secret,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ref10::sc_reduce32;
    use crate::ring::{derive_public_key, derive_secret_key, generate_key_derivation, underive_public_key};

    fn h(s: &str) -> [u8; 32] {
        hex::decode(s).unwrap().try_into().unwrap()
    }

    fn master() -> ([u8; 32], [u8; 32], [u8; 32]) {
        let mut a = [0x11u8; 32];
        sc_reduce32(&mut a);
        let mut b = [0x22u8; 32];
        sc_reduce32(&mut b);
        let big_b = secret_key_to_public_key(&b);
        (a, b, big_b)
    }

    // Generated by fuego-suite's Crypto::deriveSubAddressKeys (subaddress.cpp) for
    // a = sc_reduce32(0x11 * 32), b = sc_reduce32(0x22 * 32): (major, minor, D, C, b + m).
    const SUITE_VECTORS: &[(u32, u32, &str, &str, &str)] = &[
        (0, 1, "98408322cb0bf2a7a789bc8835d427bcf968b032ca232bd274567d63e4b48bd0", "857eed804ff087b97f87848f6493e87257a8c5203cb9f422f6e7a7d8a4d299f3", "6310c7111d4654329494b53bf6257978693f27fc44c187c2e98e353d561d9e0c"),
        (0, 2, "98825900e6c45c16e92290e0b0905c7942b72e634bb6f7ebaca594c4db8a8fb3", "857eed804ff087b97f87848f6493e87257a8c5203cb9f422f6e7a7d8a4d299f3", "6ed94b5b5e2ead9cd8b1c273a560837ee59c36d8e06a1bf73559604c6577890c"),
        (0, 7, "0de94268cf024e0e37b5d96b65caefe2a4e2f5f90761b5bc798dda04b477ac57", "857eed804ff087b97f87848f6493e87257a8c5203cb9f422f6e7a7d8a4d299f3", "c8600a92faf1285a91bfe695d86d6bc0288c81f25f432c6865f56c7525e0d903"),
        (1, 0, "2a2687a3273321a16718abe09bb7b4848cfb29ace5782824049c4b519de5c25b", "857eed804ff087b97f87848f6493e87257a8c5203cb9f422f6e7a7d8a4d299f3", "5bc54bcf4d3a7b6f6435e12a98b7442f003f21a3a3c0628ed149edde2a495008"),
        (3, 42, "a25c0ed0c19342dbf59d403cee3442cd33155b5dd1b748dc2e300afa5a56c5c6", "857eed804ff087b97f87848f6493e87257a8c5203cb9f422f6e7a7d8a4d299f3", "7652e7119cb2b6de22754009a8d7e3ec94ebb826c7b59a43c2a1af6ed7cf8201"),
    ];

    #[test]
    fn matches_suite_derive_sub_address_keys() {
        let (a, b, big_b) = master();
        for &(major, minor, d, c, sec) in SUITE_VECTORS {
            let k = derive_subaddress_keys(&a, &big_b, Some(&b), major, minor).unwrap();
            assert_eq!(k.spend_public, h(d), "D at ({major},{minor})");
            assert_eq!(k.view_public, h(c), "C at ({major},{minor})");
            assert_eq!(k.spend_secret.unwrap(), h(sec), "b+m at ({major},{minor})");
            assert_eq!(secret_key_to_public_key(&k.spend_secret.unwrap()), k.spend_public);
        }
    }

    #[test]
    fn primary_index_refused() {
        let (a, b, big_b) = master();
        assert!(derive_subaddress_keys(&a, &big_b, Some(&b), 0, 0).is_none());
    }

    #[test]
    fn sender_output_is_found_and_spendable() {
        let (a, b, big_b) = master();
        let sub = derive_subaddress_keys(&a, &big_b, Some(&b), 0, 5).unwrap();

        // Sender: ordinary address (D, A), tx key R = rG, derivation rA.
        let mut r = [0x33u8; 32];
        sc_reduce32(&mut r);
        let big_r = secret_key_to_public_key(&r);
        let sender_d = generate_key_derivation(&sub.view_public, &r).unwrap();
        let p = derive_public_key(&sender_d, 3, &sub.spend_public).unwrap();

        // Receiver: master derivation aR recovers D from P.
        let recv_d = generate_key_derivation(&big_r, &a).unwrap();
        assert_eq!(underive_public_key(&recv_d, 3, &p).unwrap(), sub.spend_public);
        // One-time secret x = Hs(aR, i) + b + m spends P.
        let x = derive_secret_key(&recv_d, 3, &sub.spend_secret.unwrap()).unwrap();
        assert_eq!(secret_key_to_public_key(&x), p);
    }
}
